apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-frivillig-skattetrekk-backend
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: "{{{ image }}}"
  port: 8080
  ingresses:
    - https://sokos-frivillig-skattetrekk-backend.intern.nav.no
    - https://sokos-frivillig-skattetrekk-backend.prod-fss-pub.nais.io
  liveness:
    path: actuator/health/liveness
    initialDelay: 30
  readiness:
    path: actuator/health/readiness
    initialDelay: 30
  startup:
    path: actuator/health/readiness
    initialDelay: 30
    failureThreshold: 30
    periodSeconds: 5
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  replicas:
    min: 2
    max: 2
  resources:
    limits:
      memory: 4096Mi
    requests:
      cpu: 100m
      memory: 512Mi
  prometheus:
    enabled: true
    path: actuator/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  webproxy: true
  accessPolicy:
    inbound:
      rules:
        - application: sokos-frivillig-skattetrekk-frontend
          namespace: okonomi
          cluster: prod-gcp
    outbound:
      rules:
        - application: sokos-oppdrag-proxy
          namespace: okonomi
        - application: logging
          namespace: nais-system

  env:
    - name: SPRING_PROFILES_ACTIVE
      value: default
    - name: TREKK_URL
      value: http://sokos-oppdrag-proxy.okonomi.svc.nais.local
    - name: TREKK_SCOPE
      value: api://prod-fss.okonomi.sokos-oppdrag-proxy/.default
    - name: TREKK_AUDIENCE
      value: prod-fss:okonomi:sokos-oppdrag-proxy
