apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: skattetrekk-backend
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: "{{{ image }}}"
  port: 8080
  ingresses:
    - https://skattetrekk-backend.intern.nav.no
    - https://skattetrekk-backend.prod-fss-pub.nais.io
  liveness:
    path: actuator/health/liveness
    initialDelay: 30
  readiness:
    path: actuator/health/readiness
    initialDelay: 30
  startup:
    path: actuator/health/readiness
    initialDelay: 30
    failureThreshold: 30
    periodSeconds: 5
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  secureLogs:
    enabled: true
  prometheus:
    enabled: true
    path: actuator/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: "grafana-lgtm"
        - id: "elastic-apm"
    logging:
      destinations:
        - id: elastic
        - id: loki
  webproxy: true
  accessPolicy:
    inbound:
      rules:
        - application: skattetrekk-frontend
          namespace: okonomi
          cluster: prod-gcp
    outbound:
      rules:
        - application: oppdrag-rest-proxy
          namespace: pensjondeployer
        - application: pensjon-representasjon
          namespace: pensjon-person

  env:
    - name: LOGGING_CONFIG
      value: classpath:logback-json.xml
    - name: PDL_URL
      value: http://pdl-api.pdl.svc.nais.local/graphql
    - name: PDL_SCOPE
      value: api://prod-fss.pdl.pdl-api/.default
    - name: PDL_AUDIENCE
      value: prod-fss:pdl:pdl-api
    - name: FULLMAKT_URL
      value: http://pensjon-representasjon.pensjon-person.svc.nais.local
    - name: FULLMAKT_SCOPE
      value: api://prod-fss.pensjon-person.pensjon-representasjon/.default
    - name: FULLMAKT_AUDIENCE
      value: prod-fss:pensjon-person:pensjon-representasjon
    - name: TREKK_URL
      value: http://oppdrag-rest-proxy.pensjondeployer.svc.nais.local
    - name: TREKK_SCOPE
      value: api://prod-fss.pensjondeployer.oppdrag-rest-proxy/.default
    - name: TREKK_AUDIENCE
      value: prod-fss:pensjondeployer:oppdrag-rest-proxy
    - name: NORG2_URL
      value: https://norg2.intern.nav.no/norg2/api/v1
    - name: NORG2_SCOPE
      value: api://prod-gcp.org.norg2/.default
    - name: NORG2_AUDIENCE
      value: prod-gcp:org:norg2
