apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-frivillig-skattetrekk-backend-q2
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: "{{{ image }}}"
  port: 8080
  ingresses:
    - https://sokos-frivillig-skattetrekk-backend-q2.intern.dev.nav.no
    - https://sokos-frivillig-skattetrekk-backend-q2.dev-fss-pub.nais.io
  liveness:
    path: actuator/health/liveness
    initialDelay: 30
  readiness:
    path: actuator/health/readiness
    initialDelay: 30
  startup:
    path: actuator/health/readiness
    initialDelay: 30
    failureThreshold: 30
    periodSeconds: 5
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  secureLogs:
    enabled: true
  prometheus:
    enabled: true
    path: actuator/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: "grafana-lgtm"
        - id: "elastic-apm"
    logging:
      destinations:
        - id: elastic
        - id: loki
  webproxy: true
  accessPolicy:
    inbound:
      rules:
        - application: sokos-frivillig-skattetrekk-frontend-q2
          namespace: okonomi
          cluster: dev-gcp
        - application: tokenx-token-generator
          namespace: nais
          cluster: dev-gcp
        - application: azure-token-generator
          namespace: nais
          cluster: dev-gcp
    outbound:
      rules:
        - application: sokos-oppdrag-proxy-q2
          namespace: okonomi
        - application: pensjon-representasjon-q2
          namespace: pensjon-person

  env:
    - name: LOGGING_CONFIG
      value: classpath:logback-json.xml
    - name: PDL_URL
      value: http://pdl-api.pdl.svc.nais.local/graphql
    - name: PDL_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default
    - name: PDL_AUDIENCE
      value: dev-fss:pdl:pdl-api
    - name: FULLMAKT_URL
      value: http://pensjon-representasjon-q2.pensjon-person.svc.nais.local
    - name: FULLMAKT_SCOPE
      value: api://dev-fss.pensjon-person.pensjon-representasjon-q2/.default
    - name: FULLMAKT_AUDIENCE
      value: dev-fss:pensjon-person:pensjon-representasjon-q2
    - name: TREKK_URL
      value: http://sokos-oppdrag-proxy-q2.okonomi.svc.nais.local
    - name: TREKK_SCOPE
      value: api://dev-fss.okonomi.sokos-oppdrag-proxy-q2/.default
    - name: TREKK_AUDIENCE
      value: dev-fss:okonomi:sokos-oppdrag-proxy-q2
    - name: NORG2_URL
      value: https://norg2.intern.dev.nav.no/norg2/api/v1
    - name: NORG2_SCOPE
      value: api://dev-gcp.org.norg2/.default
    - name: NORG2_AUDIENCE
      value: dev-gcp:org:norg2
