apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: skattetrekk-frontend-q2
  namespace: okonomi
  labels:
    team: okonomi
  annotations:
    nais.io/run-as-user: "101" # nginx
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
spec:
  image: "{{{ image }}}"
  port: 8080
  ingresses:
    - https://skattetrekk-frontend-q2.intern.dev.nav.no
    - https://skattetrekk-frontend-q2.ansatt.dev.nav.no
  replicas:
    min: 1
    max: 2
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
    periodSeconds: 20
    failureThreshold: 5
    timeout: 1
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
    periodSeconds: 20
    failureThreshold: 5
    timeout: 1
  frontend:
    generatedConfig:
      mountPath: /usr/share/nginx/html/assets/nais.js
  idporten:
    enabled: true
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /internal/ping
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: wonderwalled-idporten
          namespace: aura
  env:
    - name: "VITE_DECORATOR_URL"
      value: "https://dekoratoren.ekstern.dev.nav.no"
    - name: "SKATTETREKK_BACKEND_URL"
      value: "https://skattetrekk-backend-q2.dev-fss-pub.nais.io"
    - name: "SKATTETREKK_BACKEND_SCOPE"
      value: "api://dev-fss.okonomi.skattetrekk-backend-q2/.default"
    - name: "SKATTETREKK_BACKEND_AUDIENCE"
      value: "dev-fss:okonomi:skattetrekk-backend-q2"
    - name: "REPRESENTASJON_BANNER_URL"
      value: "https://representasjon-banner-frontend-borger-q2.intern.dev.nav.no"
