name: Build frontend

on:
  workflow_dispatch:
  push:
    paths:
      - 'skattetrekk-frontend/**'

jobs:
  build-frontend-and-publish-docker:
    name: Build frontend application
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./skattetrekk-frontend
    permissions:
      actions: read
      contents: read
      id-token: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://npm.pkg.github.com'

      - name: Cache node modules
        id: cache-node
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: Build frontend application
        run: npm ci && npm run build
        env:
          FARO_TELEMETRY_URL: 'https://telemetry.ekstern.dev.nav.no/collect'
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: docker-build-push
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: okonomi
          dockerfile: ./skattetrekk-frontend/.docker/Dockerfile
          image_suffix: skattetrekk-frontend
