name: Build backend

on:
  workflow_dispatch:
  push:
    paths:
      - 'skattetrekk-backend/**'

env:
  BACKEND_IMAGE: ghcr.io/${{ github.repository }}/skattetrekk-backend

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      id-token: write
      packages: write
      security-events: write
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 21

      - name: Build
        shell: bash
        run: |
          mvn package --no-transfer-progress --batch-mode

      - name: docker-build-push
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: pensjonselvbetjening
          dockerfile: ./skattetrekk-backend/Dockerfile
          docker_context: ./skattetrekk-backend
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
