name: "Deploy to dev-gcp"

on: workflow_dispatch

env:
  IMAGE_GCP: ghcr.io/${{ github.repository }}/skattetrekk-backend:${{ github.sha }}

jobs:
  deploy-to-dev-gcp:
    name: Deploy to dev-gcp
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      checks: "write"
      id-token: "write"
      packages: "write"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 21
      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B package --file pom.xml
      - name: Build Docker image
        run: |
          docker build -f ./skattetrekk-backend/Dockerfile -t ${IMAGE_GCP} .
      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./skattetrekk-backend/Dockerfile
          push: true
          tags: ${{ env.IMAGE_GCP }}
      - name: Generate NAIS variables GCP
        run: |
          cat > ./skattetrekk-backend/.nais/vars-gcp.yaml <<EOF
          namespace: okonomi
          image_gcp: $IMAGE_GCP
          EOF
      - name: Deploy to dev-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: ./skattetrekk-backend/.nais/.nais-q2.yml
          VARS: ./skattetrekk-backend/.nais/vars-gcp.yaml