name: Deploy application manual

on:
  workflow_dispatch:

env:
  TZ: Europe/Oslo

permissions:
  contents: "write"
  id-token: "write"

jobs:
  build:
    name: Build/test & push image
    uses: navikt/mob-gha-workflows/.github/workflows/gradle-build-push-image.yaml@main
    secrets: inherit
    with:
      gradle-task: './gradlew --configuration-cache build'
      image-tag: snapshot

  deploy-dev-q2:
    needs: build
    name: Deploy to dev-fss-q2
    uses: navikt/mob-gha-workflows/.github/workflows/nais-app-deploy.yaml@main
    with:
      cluster: dev-fss
      resource: .nais/naiserator-q2.yaml
      image: ${{ needs.build.outputs.image }}